language: r
cache: packages

os:
  - linux
  - osx

env:
  - JULIA="10"
  - JULIA="11"
  - JULIA="12"
  - JULIA="13"

r:
  - oldrel
  - release
  - devel
  - 3.6.2
  - 3.6.1
  - 3.6.0
  - 3.5.3
  - 3.5.2
  - 3.5.1
  - 3.5.0
  - 3.4.4
  - 3.4.3
  - 3.4.2
  - 3.4.1
  - 3.4.0

addons:
  apt:
    sources: [ 'ubuntu-toolchain-r-test']
    packages: ['libstdc++6']

r_packages:
  - covr

before_install:
  - mkdir -p ~/Downloads

  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ $JULIA == "10" ]; then curl -L https://julialang-s3.julialang.org/bin/linux/x64/1.0/julia-1.0-latest-linux-x86_64.tar.gz -o "$HOME/Downloads/julia.tar.gz"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ $JULIA == "11" ]; then curl -L https://julialang-s3.julialang.org/bin/linux/x64/1.1/julia-1.1-latest-linux-x86_64.tar.gz -o "$HOME/Downloads/julia.tar.gz"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ $JULIA == "12" ]; then curl -L https://julialang-s3.julialang.org/bin/linux/x64/1.2/julia-1.2-latest-linux-x86_64.tar.gz -o "$HOME/Downloads/julia.tar.gz"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ $JULIA == "13" ]; then curl -L https://julialang-s3.julialang.org/bin/linux/x64/1.3/julia-1.3-latest-linux-x86_64.tar.gz -o "$HOME/Downloads/julia.tar.gz"; fi

  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then tar xzf "$HOME/Downloads/julia.tar.gz" -C "$HOME/Downloads"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cp -r "$(find "$HOME/Downloads" -maxdepth 2 -name "julia*" -type d | head -n 1)" "$HOME/julia"; fi

  - if [ "$TRAVIS_OS_NAME" == "osx" ] && [ $JULIA == "10" ]; then curl -L https://julialang-s3.julialang.org/bin/mac/x64/1.0/julia-1.0-latest-mac64.dmg -o "$HOME/Downloads/julia.dmg"; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ] && [ $JULIA == "11" ]; then curl -L https://julialang-s3.julialang.org/bin/mac/x64/1.1/julia-1.1-latest-mac64.dmg -o "$HOME/Downloads/julia.dmg"; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ] && [ $JULIA == "12" ]; then curl -L https://julialang-s3.julialang.org/bin/mac/x64/1.2/julia-1.2-latest-mac64.dmg -o "$HOME/Downloads/julia.dmg"; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ] && [ $JULIA == "13" ]; then curl -L https://julialang-s3.julialang.org/bin/mac/x64/1.3/julia-1.3-latest-mac64.dmg -o "$HOME/Downloads/julia.dmg"; fi

  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then hdiutil attach ~/Downloads/julia.dmg; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cp -r /Volumes/Julia*/Julia*/Contents/Resources/julia $HOME/julia; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then hdiutil detach -force /Volumes/Julia*; fi

  - rm -rf ~/Downloads/julia*
  - export PATH="$HOME/julia/bin:$PATH"

  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export R_LD_LIBRARY_PATH="$(R RHOME)/lib:$HOME/julia/lib/julia"; fi

after_success:
  - Rscript -e 'library(covr); codecov()'
